[config]
type = "pipeline"
chartbook_format_version = "0.0.2"

[site]
title = "Treasury Spot-Futures"
author = "George Lord, Max Zhalilo"
copyright = "2025"
logo_path = ""
favicon_path = ""

[pipeline]
id = "TR"
pipeline_name = "Treasury Spot-Futures"
pipeline_description = "A data science project"
lead_pipeline_developer = "George Lord, Max Zhalilo"
contributors = ["George Lord, Max Zhalilo"]
software_modules_command = "module load anaconda3/3.11.4 TeXLive/2023"
runs_on_grid_or_windows_or_other = "Windows/Linux/MacOS"
git_repo_URL = ""
README_file_path = "./README.md"

[notebooks]


[notebooks.01_example_notebook_interactive]
notebook_name = "Example Notebook Interactive"
notebook_description = "Example notebook for demonstrating how to construct a Chartbook notebook."
notebook_path = "_output/01_example_notebook_interactive.ipynb"




[dataframes]


[charts]

